version: "3"
services:
  ciclo4amongodb:
    image: mongo:latest
    container_name: "softiendamongodb"
    ports:
      - 27017:27017
  microservicioclientes:
    image: tienda:1.0
    container_name: tienda
    ports:
      - 8080:8080
    links:
      - softiendamongodb      